### ISSUE TITLE
FR: Support self service reinstall_button_text for policy resources

### ISSUE THREAD

**Issue by mhrono** [deploymenttheory/terraform-provider-jamfpro#447] opened 2024-10-29 14:32 UTC
Self Service options for policies in the jamf GUI provide separate options for `install_button_text` and `reinstall_button_text`, but it appears the provider only supports the former. It'd be great to be able to set both of these in the HCL.

**Comment by ShocOne** [comment] 2024-10-30 15:23
field has been added into the provider and will be in release v0.4.3.

thanks

**Closed by ShocOne** 2024-10-30 15:23 UTC

**Comment by ecanault** [comment] 2024-11-06 09:29
Hi,

Not sure it's working well.

`terraform plan` goes well:

```
  # module.policies["E3772D90-64C3-4ECB-87D7-1BB06B3536F8"].jamfpro_policy.object will be updated in-place
  ~ resource "jamfpro_policy" "object" {
        id                            = "58"
        name                          = "p_install_jamfconnect_launcher"
        # (17 unchanged attributes hidden)

      ~ self_service {
          + reinstall_button_text           = "Installer"
            # (7 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

        # (2 unchanged blocks hidden)
    }
```

The state file is also correct after `apply`:

```
    self_service {
        feature_on_main_page            = false
        force_users_to_view_description = false
        install_button_text             = "Installer"
        reinstall_button_text           = "Installer"
        ... 
```

But the configuration does'nt seem to be correctly applied in Jamf Pro:

<img width="410" alt="Edit_Policy_p_install_jamfconnect_launcher__" src="https://github.com/user-attachments/assets/85ed9715-3fd1-4ce3-afc8-0aef1730b152">

Regards,
Emmanuel

**Comment by ecanault** [comment] 2024-11-06 13:30
An update doesn’t see the difference between the state file and Jamf Pro. `terraform plan` or `apply` says there is no change.

```
No changes. Your infrastructure matches the configuration.
```

The resource was created initially with version 0.4.2. I tried to delete it and recreate it from scratch: same issue.

Tried also to `destroy` all, deleting *.terraform* folder and *.tfstate* files: same issue.

**Comment by ecanault** [comment] 2024-11-25 10:31
Hi @ShocOne 

Is it possible also to reopen this one? I've tried with version 0.5.0 and the issue is still there on my side.

Regards,
Emmanuel
